### ISSUE TITLE
Add !path to check a path was not generated

### ISSUE THREAD

**Issue by paganotoni** [markbates/filetest#1]
Some buffalo generators accept --skip-xxx flags that avoid the generation of certain files.
It would be good to allow filetest to check that those files are not generated by using something like.
```json
[{
  "!path": "cmd/file.go"
}]
```

@markbates thoughts ?

**Comment by markbates** [comment]
Add it!

**Comment by paganotoni** [comment]
oh great, was just waiting for your approval, going for it! 👍

**Comment by paganotoni** [comment]
@markbates closing this one.
