### ISSUE TITLE
Wildcard/Regexp file check

### ISSUE THREAD

**Issue by paganotoni** [markbates/filetest#2]
When generating migrations with soda names of the migrations usually start with a timestamp thats hard to control in a filetest, i wonder if allowing the user to define things like:

[{
  "path": "migrations/*_create_users_table.up.fizz"
}]

could help us solve this kind of file checks.

@markbates thoughts ?

**Comment by markbates** [comment]
Add it!

**Comment by paganotoni** [comment]
Added in #4

**Comment by paganotoni** [comment]
@markbates closing this one.
